---
title: "README"
author: "kat j"
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true   
    toc_depth: 2
    number_sections: false
    preserve_yaml: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Stringtie Pipeline                                             

This is the first pipeline in the data pre-processing portion of the workflow. RNA sequencing reads are aligned to a reference genome, Then, alignments are subject to a series of Stringtie runs for assessing transcript levels of known and novel transcripts present in the data. Output includes a merged gtf file and ctab files for each sample that contain relational values for expression levels of transcripts.                                                                      

## P1: alignment                                             

- [__DGE_Pipe1_RunStar.slurm__](DGE_Pipe1_RunStar.slurm) runs RNAseq fastq files through STAR for alignment with bam files as output.                                        

## P2: stringtie round 1                                    

- [__DGE_Pipe2_StringRound1.slurm__](DGE_Pipe2_StringRound1.slurm) runs Stringtie on all bams from step 1                                                 

## P2: stringtie round 2                                            

- [__DGE_Pipe2_StringRound2.slurm__](DGE_Pipe2_StringRound2.slurm) submits [__DGE_Pipe2_Round2.py__](DGE_Pipe2_Round2.py) to the job scheduler for merging gtfs from round 1.                                           

## P2: stringtie round 3                        

- [__DGE_Pipe2_StringRound3.slurm__](DGE_Pipe2_StringRound3.slurm) runs Stringtie on the samples again, this time with the merged gtf as input.                                        




