---
title: "README"
author: "kat j"
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true   
    toc_depth: 2
    number_sections: false
    preserve_yaml: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Analysis set 2                                          

This is the last of the TARVa pipeline, adding variant call and sample information for additional tissues and conditions.  This step accepts as input the RNA-seq variant information output (vcf) from the [__Gatk RNAseq Pipeline__](../../GatkRnaSeqPipe/). Because modifications in the additional samples will only be analyzed if they match a specified group of modifications from the first analysis set, WGS data is not used. Finally, assessment of relative abundance in samples is used to more accurately inform the Variant Effect Prediction (VEP) analysis.                                                                      

## 1. Addition of information to database                                                 
  [__build2.slurm__](build2.slurm) submits [__Build_SecondSet.py__](Build_SecondSet.py) for parsing and organizing information from additional conditions and tissues, then populating the database where there are matches with highlighted information from Analysis Set 1. There are two @staticmethod scripts which Build_SecondSet.py imports as custom modules:                                    
  - [__make_secondset_tabs.py__](make_secondset_tabs.py) retrieves all sample information and populates the database.                                                            
  - [__get_second_set_counts.py__](get_second_set_counts.py) calculates counts for match instances of specified modifications in Analysis Set 1 also found in Analysis Set 2.                                                       
  
## 2. Relative Abundance                                            
  [__Rel_Abu.slurm__](Rel_Abu.slurm) submits [__tpm_analysis.py__](tpm_analysis.py) and [__fpkm_within_condition_analysis.py__](fpkm_within_condition_analysis.py) which assess Stringtie TPM values for each sample and calculate FPKM values per sample for genes and their transcripts within which specified modifications occur.  Both python scripts import read_mstrg_tab.py as a module for parsing the Stringtie output data structure and files.   
  
                                
  
  
  
